// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package bootstrap

// Injectors from wire.go:

// InitializeApp 初始化应用的所有依赖
// Wire 会根据 ProviderSet 自动生成依赖注入代码
func InitializeApp(service string, opts ...Option) (*App, error) {
	bootstrapOptions := NewOptions(opts...)
	config, err := NewConfig(service, bootstrapOptions)
	if err != nil {
		return nil, err
	}
	logger, err := NewLogger(service, config)
	if err != nil {
		return nil, err
	}
	v := NewMiddlewares(config, logger, bootstrapOptions)
	grpcServer := NewGRPCServer(config, v, bootstrapOptions)
	httpServer := NewHTTPServer(config, v, bootstrapOptions)
	v2 := NewServers(grpcServer, httpServer)
	registrar, err := NewRegistrar(config)
	if err != nil {
		return nil, err
	}
	app, err := NewKratosApp(service, config, logger, v2, registrar, bootstrapOptions)
	if err != nil {
		return nil, err
	}
	discovery, err := NewDiscovery(config)
	if err != nil {
		return nil, err
	}
	bootstrapApp := NewApp(app, config, logger, v2, registrar, discovery)
	return bootstrapApp, nil
}
